# Generated by Django 3.1.2 on 2020-11-12 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elsysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='datestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
